@echo off
echo Initializing Git repository...
git init
echo Adding all files...
git add .
echo Committing files...
git commit -m "Initial commit: rSALE Next.js project with TypeScript and shadcn/ui"
echo Adding remote repository...
git remote add origin git@github.com:MaxBaranov1993/rsnext.git
echo Pushing to GitHub...
git branch -M main
git push -u origin main
echo Done!
pause